version: '3'
services:
  pyxtermjs:
    build: .
    image: edryslabs/module-pyxtermjs:latest
    container_name: module-pyxtermjs
    ports:
      - '5000:5000'
    environment:
      - PYXTERM_CMD=zsh
